# Site settings
title: Pivot Tables
description: Tyler Myerberg
baseurl: ""
url: "https://myerberg.github.io/AdvancedDataScience/PivotTables"
# Build settings
theme: jekyll-theme-hacker
markdown: kramdown
plugins:
  - jekyll-feed
