# Site settings
title: Software Projects
description: Tyler Myerberg
baseurl: ""
url: "https://myerberg.github.io"
# Build settings
theme: jekyll-theme-hacker
markdown: kramdown
plugins:
  - jekyll-feed
